# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 733cbb4137f1412720464a38260dc468cd40a6f273e38803c234b8c6b1527678841525f64e8a0c2a7e0eb044d816a6abf4140532202ca7a8255a6b9a1bd4724d

test:
  secret_key_base: 57af01a3f3534a53584480ac7f03706df45b8ecc3db03595541ffca56c845ef2a4a6720bac7747c0d1cc10eb67f19e256e51e1e6ee84fa038243c9ff3cf040d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
